Started with const generics and replacing vec (issue #17)
Currently fails because:
error[E0277]: a value of type `[(OrderableF32, OrderableF32); N]` cannot be built from an iterator over elements of type `(OrderableF32, OrderableF32)`
   --> src\lib.rs:246:10
    |
246 |         .collect();
    |          ^^^^^^^ value of type `[(OrderableF32, OrderableF32); N]` cannot be built from `std::iter::Iterator<Item=(OrderableF32, OrderableF32)>`
    |
    = help: the trait `FromIterator<(OrderableF32, OrderableF32)>` is not implemented for `[(OrderableF32, OrderableF32); N]`